name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.263.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab85106d0f1354cd9d85d893e077d51c75489391c1332f9966f9a38ab69694a7"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
