name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.254.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "563a22713bf57bf47083fd64e3af27bfe1f18c9ea6abdc6ccbe2b8de44d855fb"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
