name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.256.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2babaffd6501abd24286a5225898ee3e13c5b760497e085e74ff1375cdbe006"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
