name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.263.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc651acbfc8aa9cbcef405346903702442beb34faef0a571f0ffaf9948f19393"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
