name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.245.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd04ee118029d3c22073db8f3de029868e5d62451cac1419cd441b6640af9d69"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
