name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.264.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b464f0d71f0f97520a80a0690cd58cbb733d114bb501a81687e7d8bb8fbfccb3"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
