name = "Create Ptd 2"
author = "Yarden-zamir"
version = "1.261.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "199e6525d3d7878ed33c325af62a74c11b13502813f10bde2e84347e932f4735"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
